inveniosoftware/react-invenio-deposit

.gitignore, src/lib/DepositApiClient.js, src/lib/DepositBootstrap/DepositBootstrap.js, src/lib/DepositBootstrap/index.js, src/lib/DepositController.js, src/lib/DepositErrorHandler.js, src/lib/DepositFormApp.js, src/lib/DepositRecordSerializer.js, src/lib/actionButtons/PublishButton/PublishButton.js, src/lib/actionButtons/PublishButton/index.js, src/lib/actionButtons/SaveButton/SaveButton.js, src/lib/actionButtons/SaveButton/index.js, src/lib/actionButtons/index.js, src/lib/components/ResourceTypeField.js, src/lib/components/TitlesField.js, src/lib/components/index.js, src/lib/connect.js, src/lib/dom.js, src/lib/index.js, src/lib/state/actions/deposit.js, src/lib/state/actions/index.js, src/lib/state/reducers/deposit.js, src/lib/state/reducers/index.js, src/lib/state/types/index.js, src/lib/store.js, src/lib/storeConfig.js
Integration of invenio-app-rdm's react_invenio_deposit code into this module. The structure is probably not right yet, but it's a start and a common branch we can pile on.
=> setup: move invenio-app-rdm code into module

src/lib/actionButtons/PublishButton/PublishButton.js, src/lib/actionButtons/SaveButton/SaveButton.js, src/lib/components/AccessRightField.js, src/lib/components/ResourceTypeField.js, src/lib/components/TitlesField.js
- card-ify access-right
- add classNames to get hooks for future styling
- display resource types' type/subtype side-by-side
- make action buttons take ui props
For https://github.com/inveniosoftware/invenio-app-rdm/pull/148
=> style: improve looks of components [more]

src/lib/DepositRecordSerializer.js, src/lib/components/CreatorOrContributorField.js, src/lib/components/TitlesField.js
- Use dropdown for language
- Commented out IdentifiersFields/affiliationsFields The fields containing identifiers are problematic. See: pending Identifiers' woes write up
inveniosoftware/invenio-rdm-records#97
inveniosoftware/invenio-rdm-records#65
inveniosoftware/invenio-rdm-records#51
inveniosoftware/rfcs#11
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/154
=> Various fixes for #154

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/CreatorOrContributorField.js, src/lib/components/IdentifierField.js
- serializes identifiers correctly
- setup test harness for DepositRecordSerializer
helps close: https://github.com/inveniosoftware/invenio-rdm-records/issues/97
closes #26
=> lib: add identifiers for creators/contributors

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/195
=> lib: clear empty default contributors

CHANGES.md, package-lock.json, package.json, src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js
=> Release v0.3.0

CHANGES.md, package-lock.json, package.json, src/lib/DepositApiClient.js, src/lib/DepositController.js
With the goal of releasing today/tomorrow, I will be merging this in when test pass. Take a look though on your time to see if we should create tickets after the fact to improve/solve things. 
Tickets for the TODOs have been created:
- https://github.com/inveniosoftware/react-invenio-deposit/issues/49
- https://github.com/inveniosoftware/react-invenio-deposit/issues/50
=> publish with new API + release

CHANGES.md, package-lock.json, package.json, src/lib/DepositApiClient.js, src/lib/DepositFormApp.js
=> client: use links from passed config and returned response

src/lib/components/IdentifierField.js
=> identifier: make scheme field clearable

package-lock.json, src/lib/DepositRecordSerializer.js, src/lib/components/CreatorOrContributorField.js, src/lib/components/TitlesField.js
- part of closing https://github.com/inveniosoftware/invenio-app-rdm/issues/349
- also lowercase various values as per recent changes in backend
- include pckage-lock.json (missing from last release)
=> titles: update to new schema

package.json, src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/ContributorsField.js, src/lib/components/DescriptionsField.js, src/lib/components/IdentifiersField.js, src/lib/components/ResourceTypeField.js, src/lib/components/TitlesField.js, src/lib/components/index.js, src/lib/record.js
Depends on https://github.com/inveniosoftware/react-invenio-forms/pull/25
=> description: add description field

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/DatesField.js, src/lib/components/DatesField.test.js, src/lib/components/PublicationDateField.js, src/lib/components/PublisherField.js, src/lib/components/index.js, src/lib/record.js
- minor tweaks to get us closer to the mockups
- the DatesField Component. We can wait to fill the functionality before merging (I will deal with it tomorrow). 
Screenshots so far:
*normal but this needs to be changed to make it show 1 date by default (a-la Creators)*
*click on Add date*
=> 12 dates field

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/fields/DatesField.js, src/lib/fields/index.js
- fill DatesField functionality (serialization...)
- add additional_titles in recordSchema to be explicit.
- closes #12
=> field: serialize DatesField appropriately

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AffiliationsField.js, src/lib/components/ContributorsField.js, src/lib/components/CreatorsField.js, src/lib/components/DescriptionsField.js, src/lib/components/IdentifiersField.js, src/lib/components/LanguagesField.js, src/lib/components/RelatedIdentifiersField.js, src/lib/components/index.js, src/lib/fields/LanguagesField.js, src/lib/record.js
Adding the below components
- Languages; closes #9 
- Alternate Identifiers; closes #17  
- Related Identifiers; closes #15
=> List of components

CHANGES.md, package-lock.json, package.json
releasing as soon as tests pass.
=> release: v0.7.6

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/SubjectsField.js, src/lib/components/SubjectsField.test.js, src/lib/components/index.js
closes #7 
This does not include plugging to an API endpoint.
=> components: add SubjectsField

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/FundingField.js, src/lib/components/FundingField.test.js, src/lib/components/VersionField.js, src/lib/components/VersionField.test.js, src/lib/components/index.js, src/lib/record.js
closes #13 
*screenshots*
On deposit page:
On record landing page:
=> component+field: add VersionField

src/lib/components/AdditionalDescriptionsField.js
=> components: fix issues with AdditionalDescriptions

src/lib/DepositApiClient.js, src/lib/DepositController.js, src/lib/DepositFileUploader.js, src/lib/DepositFormApp.js, src/lib/DepositRecordSerializer.js, src/lib/components/FileUploader/FileUploadArea.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderToolbar.js, src/lib/components/FileUploader/utils.js, src/lib/components/index.js, src/lib/state/reducers/files.js
* Initial no file metadata
* Metadata only record checked
* Initial with file metadata
* Preview checkbox allows only one row to be checked
* View on published record
* View when a file upload is in progress
closes #92 
closes #101
=> files: style file uploader views

src/lib/DepositApiClient.js, src/lib/DepositController.js, src/lib/DepositFileUploader.js, src/lib/DepositRecordSerializer.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderArea.js, src/lib/state/reducers/files.js
**NOTE**: `DepositFileUploader` is using a mocked Promise to imitate the backend response
closes #104
=> Refactor deposit file uploader

src/lib/DepositController.js, src/lib/DepositFileUploader.js, src/lib/DepositRecordSerializer.js
closes #97
closes #98 
closes #103
=> Uplooad to invenio

src/lib/components/CreatibutorsField.js
- part of closing https://github.com/inveniosoftware/invenio-rdm-records/issues/224
=> components: show 1st/last name if person, name if org

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/LanguagesField.js
=> components: add autocompletion for languages component

src/lib/components/AffiliationsField.js, src/lib/components/IdentifiersField.js
Here are some examples of how it looks like:
=> components: add autocompletion for affiliations component

CHANGES.md, LICENSE, package-lock.json, package.json, src/lib/DepositApiClient.js, src/lib/DepositController.js, src/lib/components/DeleteButton.js, src/lib/components/PublishButton/PublishButton.js, src/lib/components/SaveButton/SaveButton.js, src/lib/components/index.js, src/lib/state/actions/deposit.js, src/lib/store.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/452
=> 452 delete discard button

src/lib/DepositBootstrap/DepositBootstrap.js, src/lib/components/DepositFormTitle.js, src/lib/components/ResourceTypeField.js, src/lib/components/index.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/469
- took down the margin-top a notch. Please check if screenshots look ok.
- (started off from previous work - will need to be rebased when the other work is merged)
New Upload
Edit Upload
=> DepositFormTitle: add new component + reduce margin-top

src/lib/DepositBootstrap/DepositBootstrap.js, src/lib/components/DepositFormTitle.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/ResourceTypeField.js, src/lib/components/index.js
closes inveniosoftware/invenio-app-rdm#467
=> files: use Message for note about uploads

src/lib/components/FileUploader/FileUploaderArea.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/123
requires https://github.com/inveniosoftware/invenio-app-rdm/pull/473
=> files: center pending label

src/lib/components/License/LicenseField.js
=> license: rename add buttons

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/AffiliationsField.js, src/lib/components/DatesField.js, src/lib/components/FileUploader/FileUploaderArea.js, src/lib/components/FundingField.js, src/lib/components/IdentifiersField.js, src/lib/components/RelatedIdentifiersField.js
=> components: place onClick on button for array deletion

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/RelatedWorksField.js, src/lib/components/RelatedWorksField.test.js, src/lib/components/index.js, src/lib/record.js
- closes #86 (part 1)
- See https://github.com/inveniosoftware/invenio-app-rdm/pull/476 for invenio app rdm
=> components: rename RelatedIdentifiers to RelatedWorks

src/lib/components/DatesField.js
requires inveniosoftware/react-invenio-forms#51
It's as good as I can get it after tinkering with it a lot :/
=> DatesField: fill out full row

src/lib/components/DatesField.js
- requires https://github.com/inveniosoftware/react-invenio-forms/pull/53
- styled via https://github.com/inveniosoftware/invenio-app-rdm/pull/478
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/171
=> DatesField: add helptext

src/lib/components/AdditionalTitlesField.js, src/lib/components/DatesField.js, src/lib/components/LanguagesField.js, src/lib/components/RelatedWorksField.js, src/lib/components/ResourceTypeField.js, src/lib/components/TitlesField.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/455
Additional titles
Related works
=> components: make Additional titles + Related Works array rows fluid

src/lib/components/AdditionalTitlesField.js, src/lib/components/ComingSoonField.js, src/lib/components/DatesField.js, src/lib/components/LanguagesField.js, src/lib/components/RelatedWorksField.js, src/lib/components/ResourceTypeField.js, src/lib/components/TitlesField.js, src/lib/components/index.js
- needed for https://github.com/inveniosoftware/invenio-app-rdm/issues/480
=> ComingSoonField: add new component

src/lib/DepositController.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderToolbar.js, src/lib/components/FileUploader/index.js
=> files: upload current form if unsaved when uploading a file

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/License/LicenseResults.js
=> misc january form improvements

src/lib/components/PublicationDateField.js
closes inveniosoftware/react-invenio-deposit/issues/186
=> helptext: adding helptext for Publication date.

src/lib/components/PublicationDateField.js, src/lib/components/PublisherField.js, src/lib/components/RelatedWorksField.js, src/lib/components/VersionField.js
closes inveniosoftware/invenio-app-rdm#453
*screenshots*
=> deposit: helptexts for fields

src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderToolbar.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/190
See issue for screenshots!
=> files: fix broken label for large screens

src/lib/components/DeleteButton.js, src/lib/components/DepositFormTitle.js
- closes #195 
- requires invenio-app-rdm PR: https://github.com/inveniosoftware/invenio-app-rdm/pull/549
=> 195 title discard color

src/lib/components/Creatibutors/CreatibutorsModal.js
=> creatibutors: actionbutton dynamic content change

src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/License/LicenseField.js, src/lib/components/License/LicenseFieldItem.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/194
depends on https://github.com/inveniosoftware/invenio-app-rdm/pull/552
=> license: add drag-n-drop ordering of licenses

src/lib/components/Creatibutors/CreatibutorsModal.js
=> creatibutors: change flip switch to radiofield

src/lib/components/Creatibutors/CreatibutorsIdentifiers.js
=> creatibutors(identifiers): update placeholder

src/lib/components/Creatibutors/CreatibutorsModal.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/188
=> creatibutors: add yup schema validation

src/lib/components/AdditionalDescriptionsField.js
closes inveniosoftware/invenio-rdm-records#360
**screenshot without language field**
**screenshot with language field**
=> additionalDescription: change in the layout

src/lib/components/Access/Embargo.js, src/lib/components/Access/Embargoed.js, src/lib/components/Access/EmbargoedFiles.js, src/lib/components/Access/Public.js, src/lib/components/Access/Restricted.js, src/lib/components/Access/RestrictedFiles.js, src/lib/components/Access/index.js, src/lib/components/Access/utils.js, src/lib/components/AccessRightField.js
- This doesn't include connection to formik yet
* means no frontend interaction or backend integration
- Closes #206 
- opens new issue for formik integration
**A few screenshots (not all cases):**
Metadata-only Restricted Record
Public Record Embargoed files
Public Record embargo lifted
=> AccessRight: implement protection widget [+]

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/Access/Embargo.js, src/lib/components/Access/EmbargoCheckboxField.js, src/lib/components/Access/EmbargoDateField.js, src/lib/components/Access/ProtectionButtons.js, src/lib/components/Access/Public.js, src/lib/components/Access/RestrictedFiles.js, src/lib/components/Access/utils.js, src/lib/components/AccessRightField.js, src/lib/components/SubjectsField.test.js
- closes #218 
- still need to do full manual testing of flow to confirm everything after
=> 218 protection widget connect redux

src/lib/components/FileUploader/FileUploader.js
closes inveniosoftware/invenio-app-rdm#574
*screenshot*
=> fileuploader: changed warning text

src/lib/components/Access/Public.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/570
=> access: fix Public color

src/lib/components/AdditionalTitlesField.js
closes inveniosoftware/invenio-rdm-records#359
**screenshots**
=> additionalTitles: adds Languages field

src/lib/components/License/LicenseModal.js
partially closes inveniosoftware/invenio-app-rdm#588
**screenshots**
=> License: adds url validation for custom license link

src/lib/components/Access/utils.js
closes inveniosoftware/invenio-app-rdm#582
=> access-widget: adds icon and update placeholder

src/lib/components/VersionField.js
closes inveniosoftware/invenio-app-rdm#590
=> versionField: adds link to helptext

package-lock.json, package.json, src/lib/components/DescriptionsField.js
related to inveniosoftware/invenio-app-rdm#596
requires https://github.com/inveniosoftware/react-invenio-forms/pull/63
=> description: accept editorConfig and pass it to the RichInputField

src/lib/DepositFormApp.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/index.js, src/lib/components/NewVersionButton.js, src/lib/components/index.js, src/lib/store.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/685
=> files: add new version button

src/lib/components/FileUploader/FileUploaderArea.js
closes inveniosoftware/invenio-app-rdm#706
Deposit Page:
Landing Page:
=> files: change styling of md5 checksum text

src/lib/DepositRecordSerializer.js, src/lib/components/DeleteButton.js, src/lib/components/DepositFormTitle.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/704
=> deposit: refine form title/delete button text

src/lib/components/Creatibutors/CreatibutorsFieldItem.js
closes inveniosoftware/invenio-app-rdm#739
=> deposit: show orcid and role of creators

src/lib/components/PreviewButton.js, src/lib/components/index.js
* Adds review button
* partially closes https://github.com/inveniosoftware/invenio-app-rdm/issues/669
=> deposit: review button

src/lib/components/FormFeedback.js, src/lib/components/License/LicenseField.js, src/lib/components/RelatedWorksField.js, src/lib/utils.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/451
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/213
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/674
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/483
**Screenshot**
=> FormFeedback: display human readable error labels [+]

src/lib/components/FileUploader/FileUploader.js
- when reaching max. number of files
- when reaching max. file storage
closes inveniosoftware/invenio-app-rdm#731
- Change limits on `invenio-app-rdm` to facilitate reaching them.
```diff
diff --git a/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js b/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
index c770110..51530d8 100644
--- a/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
+++ b/invenio_app_rdm/theme/assets/semantic-ui/js/invenio_app_rdm/deposit/RDMDepositForm.js
@@ -306,8 +306,8 @@ export class RDMDepositForm extends Component {
<FileUploader
isDraftRecord={!this.props.record.is_published}
quota={{
-                      maxFiles: 100,
- …
```
=> deposit: display warning when file limits reached

src/lib/components/DeleteButton.js, src/lib/components/PreviewButton.js, src/lib/components/PublishButton.js
Fix loading state of the buttons
=> buttons: Fixes loading state

src/lib/components/AccessRightField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/776
=> files: fix file restriction display

src/lib/components/PreviewButton.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/783
=> preview: fix Safari bug

src/lib/components/FileUploader/FileUploader.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/784
=> depositForm: Fix "import files" button style

src/lib/components/Access/utils.js, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/Creatibutors/CreatibutorsIdentifiers.js, src/lib/components/Creatibutors/CreatibutorsModal.js, src/lib/components/DatesField.js, src/lib/components/FundingField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/RelatedWorksField.js, src/lib/components/TitlesField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/792
=> fields: Optimize fields

src/lib/components/FormFeedback.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/791
=> depositForm: add display of embargo errors

src/lib/components/Creatibutors/CreatibutorsModal.js
Remove given name as a required field in add creator.
Closes https://github.com/inveniosoftware/invenio-rdm-records/issues/548
=> CreatibutorsModal

src/lib/components/Identifiers/PIDField.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/820
=> Add help text to clear reserved DOI

CHANGES.md, package-lock.json, package.json, src/lib/DepositRecordSerializer.js, src/lib/components/ResourceTypeField.js, src/lib/components/ResourceTypeField.test.js, src/lib/fields/VocabularyField.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/840 in part
- releases react-invenio-deposit line for May
=> resource_type: adapt to vocabulary transition

src/lib/DepositFileUploader.js
=> upload: fix link URL when uploading multiple files

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/fields/ArrayFieldWithVocabulary.js, src/lib/fields/index.js
* Adds serialization of resource_type vocabulary
of related_identifiers
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/864
=> deposit form: fix serialization

src/lib/components/ResourceTypeField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/888
Working on chrome and firefox.
=> resource_type: fix sort issue

src/lib/components/Access/Embargo.js, src/lib/components/Access/Embargoed.js, src/lib/components/Access/EmbargoedFiles.js, src/lib/components/Access/EmbargoedMetadataOnly.js, src/lib/components/Access/PublicFiles.js, src/lib/components/Access/PublicMetadataOnly.js, src/lib/components/Access/Restricted.js, src/lib/components/Access/RestrictedFiles.js, src/lib/components/Access/RestrictedMetadataOnly.js, src/lib/components/Access/utils.js, src/lib/components/AccessRightField.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/400 
https://user-images.githubusercontent.com/15194802/121338295-a8e8dd80-c91d-11eb-8a14-9b4a85b9f942.mp4
=> deposit: Fix lifted embargo display

src/lib/components/SubjectsField.js
* partially closes https://github.com/inveniosoftware/invenio-rdm-records/issues/631
https://user-images.githubusercontent.com/15194802/121691962-dbced500-cac7-11eb-9190-aed46182264f.mp4
=> subjects: enable SubjectsField as a vocabulary

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/TitlesField.js, src/lib/fields/ArrayFieldWithVocabulary.js, src/lib/record.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/691
=> additional titles: Adds title type and languages vocabularies

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/Creatibutors/CreatibutorsField.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/670
=> Creators: Adds vocabulary field for creators

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/DescriptionsField.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/696
* needs https://github.com/inveniosoftware/invenio-app-rdm/pull/927
=> DescriptionsField: add type and language vocabularies

CHANGES.md, package-lock.json, package.json
just there to re-number the latest changes to be part of 0.15.3 rather than 0.15.2
=> release: v0.15.3

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/record.js
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/700
=> serializer: conver date type to vocab

CHANGES.md, package-lock.json, package.json, src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AffiliationsField.js, src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/Creatibutors/CreatibutorsModal.js, src/lib/fields/VocabularyField.js, src/lib/fields/index.js
requires https://github.com/inveniosoftware/react-invenio-forms/pull/82
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/919
=> affiliations: align with custom vocabulary backend

src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AffiliationsField.js, src/lib/components/SubjectsField.js, src/lib/fields/VocabularyField.js
- requires https://github.com/inveniosoftware/react-invenio-forms/pull/84
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/326
=> subjects: align with vocabulary backend

src/lib/components/PreviewButton.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/944
=> components: enable preview button to redirect on partial save

src/lib/DepositApiClient.js, src/lib/DepositFormApp.js, src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/License/LicenseField.js, src/lib/components/License/LicenseFieldItem.js, src/lib/components/License/LicenseModal.js, src/lib/fields/VocabularyField.js, src/lib/fields/index.js
* New (de)serializer for this field
* closes https://github.com/inveniosoftware/invenio-rdm-records/issues/718
* Depends https://github.com/inveniosoftware/invenio-rdm-records/pull/736
=> licenses: Adapt to vocab structure

src/lib/components/AffiliationsField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/959
https://user-images.githubusercontent.com/15194802/125963215-d42774e1-185d-45f3-869a-b2dcdde9d554.mp4
=> affiliations: Update serializer to include acronym

src/lib/components/Creatibutors/CreatibutorsField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/963
=> creatibutors: Add error display

src/lib/components/FormFeedback.js, src/lib/translations/messages/de/translations.json, src/lib/translations/messages/el/translations.json, src/lib/translations/messages/en/translations.json, src/lib/translations/messages/tr/translations.json
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/961
=> identifiers: error validation

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/DatesField.js, src/lib/utils.js
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/337
=> global: fix list options sorting

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/RelatedWorksField.js
- requires: https://github.com/inveniosoftware/react-invenio-forms/pull/87
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/966
*Additional titles*
*Alternate identifiers*
*Additional descriptions*
*Related works*
=> components: mark required fields

src/lib/components/DescriptionsField.js
- oups my bad!
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/993﻿
=> description: mark as not required

src/lib/components/FormFeedback.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/964
=> FormFeedback: remove duplicate error messages

src/lib/DepositBootstrap.js, src/lib/components/Creatibutors/CreatibutorsField.js
* Remove "enableReinitialize" formik prop
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/965
https://user-images.githubusercontent.com/15194802/126297752-9267f694-e9a7-4eb3-a10e-e3b9f33d2d0c.mp4
=> validation: enable error display on create

src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/Creatibutors/CreatibutorsFieldItem.js
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/364
=> creatibutor: improves error display

src/lib/DepositApiClient.js, src/lib/components/NewVersionButton.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/778
Fixes the following actions (deposit form related):
- Create draft
- Save draft
- Publish draft
- Delete draft
- Init files
- Upload files
- Commit files
- Delete file
- New version
=> deposit api: configure axios for csrf headers

src/lib/components/Creatibutors/CreatibutorsModal.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1005
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1005
=> creatibutors modal: Update identifiers placeholder

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/365
=> languages field: disable selecteOnBlur

src/lib/components/PreviewButton.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1051
=> preview button: only preview if saved succesffully

package-lock.json, package.json, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/Creatibutors/CreatibutorsModal.js, src/lib/components/PreviewButton.js
- creatibutors modal: Update identifiers placeholder
- languages field: disable selecteOnBlur
- preview button: only preview if saved succesffully
- release: v0.16.2
=> cherry pick 0.16.2

src/lib/components/Access/Restricted.js, src/lib/translations/messages/de/messages.po, src/lib/translations/messages/de/translations.json, src/lib/translations/messages/el/translations.json, src/lib/translations/messages/en/translations.json, src/lib/translations/messages/tr/translations.json, src/lib/translations/translations.pot
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1058
=> access: fix no space in restricted record message

src/lib/components/RelatedWorksField.js
closes inveniosoftware/invenio-app-rdm/issues/1085
=> related works: change order of identifier and scheme field

src/lib/store.js
=> files: fix check for zero sized files

README.md, src/lib/components/SubjectsField.js
- fixes a small typo in the subjects field UI
- How should I update the translations? I can add the given instructions to the readme too.
=> subjects: fix typo

package.json, src/lib/DepositRecordSerializer.js, src/lib/DepositRecordSerializer.test.js, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/DatesField.js, src/lib/components/FundingField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/RelatedWorksField.js, src/lib/fields/SchemaField.js, src/lib/fields/SchemaField.test.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1146
- ArrayFields: fix deletion of item in an ArrayField
- release: v0.17.4
- requires released: https://github.com/inveniosoftware/react-invenio-forms/pull/99
=> 1146 arrayfield item deletion

src/lib/components/License/LicenseField.js, src/lib/components/License/LicenseFieldItem.js, src/lib/components/License/LicenseModal.js
- closes #387
- refactor license passing / ui.rights updating
https://user-images.githubusercontent.com/1932651/151022644-20f306e8-ecb7-4fad-8f81-6736ecc674ee.mp4
=> rights: fix rights removal

src/lib/DepositFormApp.js, src/lib/store.js
part of https://github.com/inveniosoftware/invenio-app-rdm/pull/1258
=> deposit: store community prop in redux

src/lib/components/Communities/CommunityHeader.js
* Replaces semantic ui react Image with
Image of react-invenio-forms
=> community header: Fix missing import

src/lib/DepositController.js
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
1. …
=> deleteButton: expose success delete callback

src/lib/components/Creatibutors/CreatibutorsField.js, src/lib/components/Creatibutors/CreatibutorsFieldItem.js, src/lib/components/Creatibutors/CreatibutorsModal.js
- Addresses https://github.com/inveniosoftware/invenio-app-rdm/issues/1311
- Required by https://github.com/inveniosoftware/invenio-app-rdm/pull/1336
=> creatibutors: feature flag for names autocomplete

src/lib/components/Creatibutors/CreatibutorsField.js
Closes [#1312](https://github.com/inveniosoftware/invenio-app-rdm/issues/1312)
=> creatibutors: remove default value for given name

src/lib/components/CommunitySelectionModal/CommunityContext.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/CommunitySelectionModal/CommunitySelectionFooter.js, src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js, src/lib/components/CommunitySelectionModal/CommunitySelectionSearch.js, src/lib/components/CommunitySelectionModal/index.js, src/lib/components/index.js, src/lib/translations/messages/en/translations.json
Added a community selection modal 
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1250
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1291
=> Deposit form: Community selection modal

src/lib/components/Communities/CommunityHeader.js, src/lib/components/Communities/index.js, src/lib/state/reducers/communities.js, src/lib/store.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1292
needs  https://github.com/inveniosoftware/react-invenio-deposit/pull/424
Adds the community selection modal to the community header in the deposit form 
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s …
=> [needs #424]Deposit Form: Connect modal to header

src/lib/components/FormFeedback.js
closes: https://github.com/inveniosoftware/invenio-app-rdm/issues/1377
=> Desposit Form: remove bottom margin from the form feedback

src/lib/components/PublishButton/SubmitReviewButton.js, src/lib/components/PublishButton/SubmitReviewModal.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1466
Changed both publish button text and modal header to "Submit for review".
=> publish button: change submit text to be consistent in button and modal

src/lib/components/License/LicenseModal.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/469
=> LicenseModal: Update overridable id for toggle

src/lib/components/DepositStatus/DepositStatusBox.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/470
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1464
=> Deposit status box: Align content and change button styling

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/DatesField.js, src/lib/components/DescriptionsField.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderArea.js, src/lib/components/FileUploader/FileUploaderToolbar.js, src/lib/components/FundingField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/RelatedWorksField.js, src/lib/components/SubjectsField.js, src/lib/components/TitlesField.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1452
Related to PR https://github.com/inveniosoftware/invenio-app-rdm/pull/1459
=> improve responsiveness

src/lib/components/DepositStatus/DepositStatusBox.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1488
=> deposit status: align text

src/lib/components/Communities/CommunityHeader.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/CommunitySelectionModal/CommunitySelectionSearch.js, src/lib/components/Creatibutors/CreatibutorsModal.js, src/lib/components/License/LicenseResults.js
requires https://github.com/inveniosoftware/react-invenio-forms/pull/132
requires https://github.com/inveniosoftware/invenio-app-rdm/pull/1508
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/482
=> deposit: fix images

src/lib/components/Communities/CommunityHeader.js, src/lib/state/reducers/deposit.js
=> community: fix header logo

src/lib/components/CommunitySelectionModal/CommunityListItem.js
=> community: make community type optional

src/lib/state/actions/deposit.js
=> preview: fix preview redirect on initial draft

CHANGES.md, package-lock.json, package.json
=> release: v0.19.8

src/lib/components/Funding/CustomAwardForm.js, src/lib/components/Funding/FundingFieldItem.js, src/lib/components/Funding/FundingModal.js, src/lib/components/Funding/NoAwardResults.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1578
Needs PR https://github.com/inveniosoftware/invenio-app-rdm/pull/1633 to align the radio button and text on mobile.
- Removed accordion from additional info of custom award
- Moved message from `EmptyResults` and removed warning + info icon
- Adds spacing to award listitem
- Added accessibility for the modal
=> funding: layout improvements

src/lib/components/AccessRightField.js
* closes https://github.com/inveniosoftware/react-invenio-deposit/issues/502
=> accessRightField: restrict record if restricted community selected

CHANGES.md, package-lock.json, package.json
=> release: v0.19.9

src/lib/components/Creatibutors/CreatibutorsField.js
fixes react errors appearing the in the logs, mostly caused by incorrect prop types being passed or props being passed that are not defined/used in a child component
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository …
=> logs: clear up errors appearing in the console

src/lib/components/ResourceTypeField.js
Remove jumping when selecting resource type dropdown
closes: https://github.com/inveniosoftware/react-invenio-deposit/issues/507
=> Submission form: avoid adding resource type on blur

src/lib/components/Funding/FunderDropdown.js, src/lib/components/Funding/FundingModal.js, src/lib/components/RelatedWorksField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1637
=> dropdowns: fix missalignment

src/lib/components/PublishButton/SubmitReviewModal.js
* closes: inveniosoftware/invenio-app-rdm#1695
=> Deposits: fix escaping on confirm modal

src/lib/components/Creatibutors/CreatibutorsModal.js
ORCID, GND and ROR identifiers are rendered with icon and links.
To minimzie future breakge, any other identifiers are displayed but without icon/link.
(To avoid potential confusion - yes I did make entities called "Ocrid, Gnd" and "Orcid, Only" as test cases - it also works with real names! :grin:)
closes inveniosoftware/invenio-app-rdm#1500
**Reminder**
By using GitHub, you have …
=> Creatibutors: remove orcid dependence from deposit form autocomplete JS.

src/lib/components/Communities/CommunityHeader.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js
partly closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1704
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1681
needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1710
=> communities: fix logos having inconsistent heights

src/lib/components/License/LicenseResults.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1732
=> licenses: align item content

src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/CommunitySelectionModal/CommunitySelectionSearch.js, src/lib/components/Funding/CustomAwardForm.js, src/lib/components/Funding/FundingField.js, src/lib/fields/SchemaField.js, src/lib/fields/VocabularyField.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1518
=> translations: remove hardcoded translations

src/lib/components/Communities/CommunityHeader.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1765
=> community header: remove gap from margin on mobile

src/lib/components/FileUploader/FileUploaderArea.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/531
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1766 <<--- Screenshots available
- Added data-labels to table cells
- Removed custom classes as everything is covered in the general overrides in `invenio-app-rdm` (see linked PR)
=> file table: add labels and remove custom table-classes

src/lib/components/CommunitySelectionModal/CommunityListItem.js
closes https://github.com/inveniosoftware/invenio-communities/issues/732
=> deposit: added community visibility labels.

src/lib/components/Creatibutors/CreatibutorsModal.js
fixes https://github.com/inveniosoftware/invenio-app-rdm/issues/1737
=> creatibutors: fixed dropdown off-screen rendering

src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/DatesField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/RelatedWorksField.js
Closes https://github.com/inveniosoftware/react-invenio-deposit/issues/540
- Adds aria-label to all remove-buttons in group fields
=> group fields: add descriptive aria-label to remove-buttons

src/lib/components/Access/ProtectionButtons.js, src/lib/state/reducers/deposit.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/549
=> records: fixed record access based on community visibility.

src/lib/components/Funding/FundingModal.js
Refs https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
=> global: strings with url/Url should be URL

.gitignore, src/lib/DepositRecordSerializer.js, src/lib/fields/CustomField.js
=> rename custom to custom_fields

.gitignore, CHANGES.md, package-lock.json, package.json
=> release: v0.20.0

src/lib/components/Access/EmbargoDateField.js, src/lib/components/AccessRightField.js, src/lib/components/AdditionalDescriptionsField.js, src/lib/components/AdditionalTitlesField.js, src/lib/components/Creatibutors/CreatibutorsIdentifiers.js, src/lib/components/DatesField.js, src/lib/components/DescriptionsField.js, src/lib/components/Funding/FundingField.js, src/lib/components/Identifiers/IdentifiersField.js, src/lib/components/LanguagesField.js, src/lib/components/License/LicenseField.js, src/lib/components/PublicationDateField.js, src/lib/components/PublisherField.js, src/lib/components/RelatedWorksField.js, src/lib/components/ResourceTypeField.js, src/lib/components/SubjectsField.js, src/lib/components/TitlesField.js, src/lib/components/VersionField.js
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/563
=> global: remove default fieldPath ignore rule

package-lock.json, package.json
=> release: v0.20.3

CHANGES.md, package-lock.json, package.json, src/lib/components/License/LicenseModal.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1923
=> components: fix close modal handler

src/lib/DepositApiClient.js, src/lib/DepositFormApp.js
The implementation allows you to configure the BASE_HEADERS for other modules using the DepositFormApp and the REST
api client.
=> deposit api: Config api headers 

src/lib/components/NewVersionButton.js
closes: inveniosoftware/react-invenio-forms#168
=> Axios: Centralize imports

CHANGES.md, package-lock.json, package.json
=> release: v1.0.4

CHANGES.md, package-lock.json, package.json
=> release: v1.2.0

src/lib/components/PublishButton/SubmitReviewModal.js
=> Deposit form: allow special character in submit panel

CHANGES.md, package-lock.json, package.json, src/lib/DepositApiClient.js, src/lib/DepositBootstrap.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js, src/lib/components/PublishButton/PublishButton.js, src/lib/components/PublishButton/SubmitReviewButton.js, src/lib/components/PublishButton/SubmitReviewModal.js, src/lib/components/PublishButton/SubmitReviewOrPublishButton.js, src/lib/state/actions/deposit.js, src/lib/state/reducers/deposit.js, src/lib/state/reducers/deposit.test.js
- closes https://github.com/inveniosoftware/invenio-communities/issues/871
=> implement direct publish

src/lib/components/Journal.js, src/lib/components/index.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1191
=> contrib: added journal custom field.

src/lib/components/Meeting.js, src/lib/components/index.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1211
=> contrib: added meeting custom field

src/lib/components/Imprint.js, src/lib/components/index.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1215
=> contrib: added imprint custom field.

src/lib/components/FileUploader/FileUploaderToolbar.js
- Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2021.
**Reminder**
1. You license your contribution under the same terms as the …
=> components: convert config to snake-case

src/lib/state/actions/deposit.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2125
* needs https://github.com/inveniosoftware/invenio-rdm-records/pull/1237
=> deposit: updates redirect links on submit review

src/lib/state/reducers/deposit.js, src/lib/state/reducers/deposit.test.js
* closes inveniosoftware/invenio-app-rdm#2060
=> community-inclusion: rename permission

src/lib/components/Communities/index.js, src/lib/components/Communities/labels/CommunityTypeLabel.js, src/lib/components/Communities/labels/RestrictedLabel.js, src/lib/components/Communities/labels/index.js, src/lib/components/Communities/search/CommunityCompactItem.js, src/lib/components/Communities/search/CommunityCompactItemComputer.js, src/lib/components/Communities/search/CommunityCompactItemMobile.js, src/lib/components/Communities/search/index.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/index.js
* this is a temporary change, in a long term we won't duplicate these components
* closes https://github.com/inveniosoftware/invenio-communities/issues/912
=> community: refactor components to match the invenio_community

src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderToolbar.js, src/lib/components/FileUploader/index.js, src/lib/components/index.js
* closes https://github.com/zenodo/who-rdm/issues/58
=> FileUploader: Add overridable

src/lib/components/Imprint.js, src/lib/components/Journal.js, src/lib/components/Meeting.js, src/lib/components/Thesis.js, src/lib/components/index.js
closes https://github.com/inveniosoftware/invenio-rdm-records/issues/1232
=> components: updated custom fields components.

CHANGES.md, package-lock.json, package.json, src/lib/components/AccessRightField.js, src/lib/components/DepositStatus/DepositStatusBox.js, src/lib/state/reducers/deposit.js, src/lib/state/reducers/deposit.test.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2063
=> resolve deleted communities

package-lock.json, src/lib/components/Communities/CommunityHeader.js, src/lib/components/CommunitySelectionModal/CommunityListItem.js, src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js, src/lib/components/CommunitySelectionModal/CommunitySelectionSearch.js, src/lib/components/CommunitySelectionModal/index.js, src/lib/components/PublishButton/SubmitReviewModal.js, src/lib/components/PublishButton/SubmitReviewOrPublishButton.js, src/lib/components/PublishButton/index.js, src/lib/components/index.js
* Add configurable appName for RSK
* Add configurable options to selection modal
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
=> Add overradible community modal

src/lib/components/Communities/search/CommunityCompactItemComputer.js, src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2075
=> assets: community selection modal optional trigger

package-lock.json, src/lib/components/Communities/search/CommunityCompactItemComputer.js, src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js, src/lib/components/CommunitySelectionModal/CommunitySelectionSearch.js, src/lib/components/PublishButton/SubmitReviewModal.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2076
=> community: allow search filters on modal

src/lib/components/Access/EmbargoDateField.js, src/lib/components/FileUploader/FileUploader.js, src/lib/components/FileUploader/FileUploaderToolbar.js, src/lib/components/Funding/CustomAwardForm.js
* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2162
=> translations: fix string concatenation

CHANGES.md, package-lock.json, package.json
=> release: v2.6.1

.gitignore, CHANGES.md, package-lock.json, package.json
This is a WIP until https://github.com/inveniosoftware/react-invenio-forms/pull/205 is merged so that this repo's package-lock.json can be appropriately generated.
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-l …
=> fix yup dependency compatibility with v9 LTS

src/setupTests.js
CI tests are broken since commit 89834c3.
This PR fixes the tests by mocking `window.matchMedia` (as for instance done in [`react-invenio-app-ils`](https://github.com/inveniosoftware/react-invenio-app-ils/blob/master/src/setupTests.js)).
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contr …
=> tests: fix window.matchMedia is not a function
