- CHANGES.md
- package-lock.json
- package.json
- src/lib/DepositController.js
- src/lib/DepositRecordSerializer.js
- src/lib/components/TitlesField.js
- closes #49 
- closes #50 
- passes a publication_date now that the backend doesn't default to one
- bumps to v0.5.X line
This is part of making a working August release and will be merged and deployed when it passes.
> api: use api's response links to redirect

- src/lib/DepositController.js
- src/lib/DepositErrorHandler.js
- src/lib/DepositRecordSerializer.js
- src/lib/DepositRecordSerializer.test.js
- src/lib/components/AccessRightField.js
- src/lib/components/CreatorOrContributorField.js
- src/lib/components/CreatorsField.js
- src/lib/components/IdentifierField.js
- src/lib/components/ResourceTypeField.js
- src/lib/components/TitlesField.js
- src/lib/state/actions/deposit.js
**EDIT**: See comment about it not being rebased. I leave it up to you to decide.
work in progress of frontend errors. Here is a screenshot of how things look like currently:
Co need:
- https://github.com/inveniosoftware/invenio-app-rdm/pull/293
- https://github.com/inveniosoftware/invenio-rdm-records/pull/182
To note:
- I replaced "family name" / "given name" by "Name" because the backend does validation against name and it's simpler for now to get both person and organization dealt with in 1 swoop.
Things that need to be done:
- Not send a contributor that is empty except for `type` by default: this makes the backend validate it and return an error on the frontend.
- Convert machine values to human labels for access radio button. I think this conversion should take place on the …
> errors: improve frontend handling of errors

- src/lib/DepositApiClient.js
- src/lib/DepositBootstrap/DepositBootstrap.js
- src/lib/DepositController.js
- src/lib/DepositFileUploader.js
- src/lib/components/FileUploader/FileUploader.js
- src/lib/components/FileUploader/FileUploaderToolbar.js
- src/lib/components/FileUploader/index.js
- src/lib/state/actions/files.js
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/147
- hides rest of file upload when metadata-only is clicked
(font size change in invenio-app-rdm)
- refactors some code a little / more to come
> files: don't clear form when clicking metadata-only

- src/lib/components/ResourceTypeField.js
- closes #78 
Also include a lot of improvements:
- Use FastField (quite satisfying to see this field's re-rendering
NOT triggered by every keystroke in another field).
- Display icon of selected option in the selected field
- Display error correctly
Icons:
Error:
> resource_type field: merge dual dropdown into one [+]

- src/lib/components/License/LicenseField.js
- src/lib/components/License/LicenseModal.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/463
closes https://github.com/inveniosoftware/react-invenio-deposit/issues/152
* Makes also modal content scrollable
> license: split dropdown to two buttons

- src/lib/components/RelatedWorksField.js
- src/lib/components/ResourceTypeField.js
(note) This component is used in both (top-level) and (sub-level) fields.
closes #88
> resoucetypefield: create label without FieldLabel

- src/lib/components/License/LicenseField.js
- src/lib/components/License/LicenseFieldItem.js
- src/lib/components/License/LicenseModal.js
LicenseField: truncate the description 
* custom license filed 'link' check - and render the 'Read more'
closes inveniosoftware/invenio-app-rdm#530
related to https://github.com/inveniosoftware/invenio-app-rdm/pull/553
*screenshots*
> licenses: truncate description

- src/lib/components/FormFeedback.js
- closes https://github.com/inveniosoftware/invenio-rdm-records/issues/393
- removes the Formik wrapper around Feedback since unnecessary (redux provides everything): helps reduce lag in form interaction.
> FormFeedback: hide ul if no errors

- src/lib/components/License/LicenseFieldItem.js
adding space only when there is a description.
closes inveniosoftware/invenio-app-rdm#584
**screenshot**
> bugfix: show readmore when no description

- src/lib/components/Creatibutors/CreatibutorsModal.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/670
The family Name / name input field is focus when
* You open the modal for adding a new creatibutor
* You edit an existing creatibutor
* You click `Save and add another`
* You change values between "Person" and "Organization"
> creatibutors: focus on family Name/name on modal open

- src/lib/components/FileUploader/FileUploader.js
closes  https://github.com/inveniosoftware/invenio-app-rdm/issues/721
> fileUploader: add back warning message if draft upload

- src/lib/DepositController.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/736
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/456
Provides some feedback to the end-user that files are missing while trying to save the draft. Result:
> deposit-form: show warning to user if files are missing while saving draft

- src/lib/components/Access/EmbargoedMetadataOnly.js
- src/lib/components/Access/PublicFiles.js
- src/lib/components/Access/PublicMetadataOnly.js
- src/lib/components/Access/Restricted.js
- src/lib/components/Access/RestrictedMetadataOnly.js
- src/lib/components/Access/index.js
- src/lib/components/AccessRightField.js
- src/lib/components/FileUploader/FileUploaderToolbar.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/740
Screenshot
> ProtectionWidget: show files section unless metadata only

- src/lib/components/SaveButton.js
**Edit May 12 2021**
Thanks to @zzacharo + @ntarocco : now using `scrollTo` (I was looking at `scroll` before https://developer.mozilla.org/en-US/docs/Web/API/Window/scroll and lamenting the Safari lack of support :facepalm: ). Though it would be good for someone with Safari to doublecheck it. (below is new video on Firefox). No other dependencies.
- closes https://github.com/inveniosoftware/react-invenio-deposit/issues/281
https://user-images.githubusercontent.com/1932651/117978899-59a09480-b300-11eb-8074-2b935e35ebfb.mp4
> SaveButton: scroll to top after saved

- .tx/config
- getTextConverter.js
- i18next-scanner.config.js
- package-lock.json
- package.json
- rollup.config.js
- src/lib/components/DepositFormTitle.js
- src/lib/components/FileUploader/FileUploaderToolbar.js
- src/lib/i18next.js
- src/lib/index.js
- src/lib/translations/de/messages.po
- src/lib/translations/de/translations.json
- src/lib/translations/en/messages.po
- src/lib/translations/en/translations.json
- src/lib/translations/tr/messages.po
- src/lib/translations/tr/translations.json
- src/lib/translations/translations.pot
related issue inveniosoftware/react-invenio-forms/issues/6
https://user-images.githubusercontent.com/44528277/122896820-bf455f00-d349-11eb-9a72-1fb4d4d12ba9.mp4
*  `i18next` 
* `i18next-browser-languagedetector` (detect user language)
* `i18next-scanner` (extract translation keys/values)
* `i18next-conv` (converts files from gettext (.mo/.po) to i18next's json format and vice versa)
import created instance in your package.
`import i18next from '../i18next';`
Mark for translation
``` diff
--- <List.Item>Storage available</List.Item>
+++ <List.Item>{i18next.t('Storage available')}</List.Item>
```
To scan your code, extract translation keys/values, and merge them into i18n resource files.
```npm
npm run i18n-scan
```
converts source language file from `JSON` to `.pot`
```npm
npm run …
```
> i18n: adds translation support

- CHANGES.md
- package-lock.json
- package.json
- src/lib/components/SubjectsField.js
- SubjectsField: filter suggest by subtype
* Also first pass at updated UX. This turned out to be easier to implement than option 4
- release: v0.15.2
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/918 in part
- closes old https://github.com/inveniosoftware/invenio-app-rdm/issues/533
> SubjectsField: filter by subtype

- CHANGES.md
- package-lock.json
- package.json
- src/lib/components/SubjectsField.js
- closes #330 
- fix label bug
- display scheme next to autocompleted entry
- will need to revisit for initial subjects when landing page work is done
so it can be re-used
> subjects: update SubjectsField component [+]

- src/lib/components/Creatibutors/CreatibutorsModal.js
- closes https://github.com/inveniosoftware/invenio-app-rdm/issues/960
* reopens modal when saving and adding
another one to unmount and mount again
the components and reset their state
https://user-images.githubusercontent.com/15194802/123294630-514d9300-d515-11eb-889e-b479088ccb50.mp4
https://user-images.githubusercontent.com/15194802/123294634-527ec000-d515-11eb-9500-b680db6659a2.mp4
> creatibutors: fix modal bug

- src/lib/components/License/LicenseModal.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1017
> license: use 'Search' as placeholder

- src/lib/components/PreviewButton.js
- src/lib/components/SaveButton.js
closes inveniosoftware/invenio-app-rdm#1012
The labels for SaveButton & PreviewButtons are now align to the center.
> ActionButton: align label to center

- src/lib/components/Creatibutors/CreatibutorsFieldItem.js
This PR addresses this bug: https://github.com/inveniosoftware/invenio-app-rdm/issues/1144
- Standardizes classname (with rest of site)
- hardcodes width and height to meet ORCID's branding guidelines
- Alt tag for a11y
- Adds span tag wrapper for ease of styling
> ORCID icon: size fixed

- src/lib/components/License/LicenseResults.js
This PR fixes an issue with `LicenseResults` component. The item's `Header` has a property `size` which accepts `small` as a value. Nonetheless, `small mt-0` is being passed which yields the following warning:
```
Warning: Failed prop type: Invalid prop `size` of value `small mt-0` supplied to `Header`, expected one of ["tiny", "small", ...] 
```
> License header has invalid size 'mt-0'

- src/lib/components/FileUploader/FileUploader.js
- src/lib/components/FileUploader/FileUploaderArea.js
- src/lib/components/FileUploader/FileUploaderToolbar.js
- src/lib/components/FileUploader/utils.js
Until now, the file sizes were always displayed in decimal format, i.e. powers of 1000 (KB, MB, GB) instead of binary format, i.e. powers of 1024 (KiB, MiB, GiB), which could be potentially incongruent with the configuration of the back-end (where usually, but not necessarily, binary file sizes are specified).
This PR enables the option to switch between decimal and binary file sizes, as desired. 
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architec …
> FileUploader: add option to switch file size display style

- src/lib/components/Creatibutors/CreatibutorsFieldItem.js
Adds GND and ROR icons next to creatibutors with these identifers set (presently only ORCID icon displayed):
Note this depends on the GND icon added in invenio-app-rdm#1470
**Reminder**
1. You …
> Add GND and ROR icons to creatibutor entries

- src/lib/components/Communities/CommunityHeader.js
> community header: make logo-image size mini

- src/lib/components/Communities/CommunityHeader.js
- src/lib/components/CommunitySelectionModal/CommunitySelectionModal.js
- src/lib/components/PublishButton/SubmitReviewOrPublishButton.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1566
Changed the `CommunitySelectionModal` to take custom props for the trigger-button. 
The reason for doing this instead of passing a custom `<Button/>` to a `trigger`-prop of the module, is because it otherwise makes it more complicated to update the aria-attributes of the button when the modal opens/closes.
> community selection modal: make triggerbutton customizable

- src/lib/components/Funding/FundingModal.js
- src/lib/components/PublishButton/SubmitReviewModal.js
Refs: https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
> i18n: Fixes strings marked for translation.

- src/lib/components/Creatibutors/CreatibutorsModal.js
- src/lib/components/DeleteButton.js
- src/lib/components/Funding/FundingModal.js
- src/lib/components/License/LicenseModal.js
- src/lib/components/PreviewButton.js
- src/lib/components/PublishButton/PublishButton.js
- src/lib/components/PublishButton/SubmitReviewButton.js
- src/lib/components/PublishButton/SubmitReviewModal.js
- src/lib/components/SaveButton.js
Refactored the action button and all dependent components to not use the ActionButton component, instead they all now use a normal SUI button component, to keep the interface clear.
needs  https://github.com/inveniosoftware/react-invenio-forms/pull/138
buttons after changes (should be the same):
> action buttons: refactor

- src/lib/DepositApiClient.js
- src/lib/components/FormFeedback.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1692
error message from backend
usual validation messages (to show they still work)
> form feedback: show error response from backend

- src/lib/DepositFilesService.js
- src/lib/state/reducers/files.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1744
The issue here boils down on how client and server deal with special characters for file names. E.g. the character á can be encoded as a single unicode character (á) or as a composite character (a ´). 
Therefore: 
- when comparing filenames between server and client, string normalisation is needed.
- when the server sends an event (e.g. `FILE_UPLOAD_CANCELLED`) to the client, the filename's string must be normalised as well. Otherwise, `state.entries` will index files by name and there will be a mismatch again and  two "files" are going to be added to `state.entries`.  
Note: this is a quick fix for this issue. Ideally we should be consistent with the encoding. In my opinion, the client should adapt to the server and …
> files: added string normalization for filenames comparison.

- src/lib/components/Funding/FundingField.js
Closes https://github.com/inveniosoftware/invenio-communities/issues/737
- Added margin-bottom to funding button
> funding field: add vertical spacing to button

- CHANGES.md
- package-lock.json
- package.json
- src/lib/components/FileUploader/index.js
- src/lib/components/index.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1716
- Exports `humanReadableBytes` to be used outside `react-invenio-deposit`.
> utils: exporting humanReadableBytes function

- src/lib/components/FormFeedback.js
- src/lib/components/Funding/FundingModal.js
- src/lib/components/PublishButton/SubmitReviewModal.js
Refs: https://github.com/inveniosoftware/invenio-app-rdm/issues/1707
> global: Fixes wording of error-messages.

- src/lib/components/FormFeedback.js
> feedback: show custom fields errors

- src/lib/components/PublishButton/PublishButton.js
- src/lib/components/PublishButton/SubmitReviewButton.js
- src/lib/components/PublishButton/SubmitReviewModal.js
- src/lib/components/PublishButton/SubmitReviewOrPublishButton.js
- part of closing https://github.com/inveniosoftware/invenio-app-rdm/issues/1204
- Integration in app-rdm: https://github.com/inveniosoftware/invenio-app-rdm/pull/1832
- The implementation goes for just injecting html directly which is fine since the html comes from the config.
- The thing left is for the community publish modal text to be added.
> Allow customization of the deposit modal

- src/lib/components/AdditionalDescriptionsField.js
- src/lib/components/DescriptionsField.js
In the deposit page, we restricted the formatting options for the **descriptions** field by specifying which plugins to *not load* in the `editorConfig`.
However, this was only used in the main **descriptions** input field but never passed to the **additional descriptions** input fields, leading to inconsistency regarding which formatting options are available.
Further, the additionally available formatting in the additional descriptions usually gets `bleach`'d out anyway.
This PR fixes that oversight, to make the input fields aligned.
Note that the icons aren't displayed in the second screenshot, because I only quickly set up a `my-site` for testing.
The first screenshot is from https://inveniordm.web.cern.ch/.
> Pass editor config to additional description fields

- src/lib/components/FileUploader/utils.js
function `humanReadableBytes` returns a string instead of JSX.
By returning `jsx` , its usage in strings (e.g. templating) was more difficult. See this [discussion](https://github.com/zenodo/zenodo-rdm/pull/89#discussion_r1022771525) for more details
> utils: refactored function to return a string instead of jsx.

- src/lib/components/Access/MetadataAccess.js
- src/lib/components/FileUploader/FileUploaderToolbar.js
Closes https://github.com/zenodo/zenodo-rdm/issues/46
Adds `<Overridable />` to `<MetadataAccess />` and metadata-only toggle button in `<FileUploaderToolbar />`
Needs https://github.com/inveniosoftware/invenio-app-rdm/pull/1970
> components: Add overridable to metadata-only button and metadata access

- src/lib/components/SubjectsField.js
Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2148
This PR updates the "Subjects" title to "Keywords and subjects" to align with the published record page.
> SubjectsField: update default label to align with record page
